// Flat ESLint config for the JS/TS workspace (extension, web, shared).
//
// Scope on purpose: this lints for CORRECTNESS, not style. Prettier owns formatting
// (`pnpm format` / `pnpm lint:format`), and `tsc --noEmit` owns types — so the rules
// here are the ones neither of those can see: unused code, unsafe fallthroughs,
// misuse of promises. Keeping the three tools non-overlapping is what stops them
// fighting each other, which is the same failure mode `.prettierignore` documents.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Generated, vendored, or owned by another tool. Mirrors .prettierignore.
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "apps/extension/src/overlay/draft-room-tokens.ts", // generated by scripts/gen-overlay-tokens.mjs
      "apps/web/next-env.d.ts", // generated by Next; its triple-slash refs are required, not a smell
      "packages/shared/schemas/**",
      "backend/**",
      "data/**",
      ".venv/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Underscore-prefixed args/vars are the repo's existing "deliberately unused"
      // convention (e.g. protocol stubs in providers/base and overlay handlers).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Repo tooling runs under Node, not in a page. Without this, `process` and
    // `console` read as undefined globals.
    files: ["scripts/**/*.mjs", "*.mjs", "**/*.config.{js,mjs,ts}"],
    languageOptions: {
      globals: { process: "readonly", console: "readonly", __dirname: "readonly" },
    },
  },
);
