"""Stage 4 of the engine: positional tiers + cliff bonuses (§3.6).

Tiers are **interpretation and a guard rail**, not an optimizer. ``assign_tiers`` sorts each
position by projected value and breaks it where the drop to the next player is larger than that
position's own typical step. ``cliff_bonuses`` then prices the last player before a break: the
drop from a tier's weakest player to the best of the next tier down, measured in MLV. Both are
precomputed into ``DraftContext``; the hot path only reads ``context.cliff_bonus[p]``.

WHY NOT GMM-on-ECR (the §3.6 letter — this is the surfaced conflict, not a silent reconcile)
--------------------------------------------------------------------------------------------
§3.6 specifies ``sklearn.mixture.GaussianMixture`` on ECR with the component count chosen by BIC.
Shipped that way, the term was **structurally dead**: measured on the live 2026 board 2026-07-26,
``cliff_bonus`` held 447 entries and every single one was exactly 0.0, so ``recommend``'s
``α·CliffBonus`` contributed 0.00 to every pick and E2's tuned α was noise. Three measurements,
each of which had to change:

* **BIC cannot find tiers in this variable.** It is a density-estimation criterion — it asks "was
  this generated by k Gaussians?" A position's value curve is smooth and monotone, not multimodal,
  so the honest answer is "by none of them" and BIC falls back to the simplest model. Measured
  argmin over the draftable top-204: **k=1** for RB, QB, TE and K (on ECR *and* on μ) and k=2 for
  WR. Over the whole 510-player board it found 8 boundaries total — all 31 defenses in ONE tier,
  a kicker tier holding exactly ONE player, and skill tiers of 25–54. Boris-Chen tiering works
  because each player carries a *distribution* of expert opinions and tiers emerge where those
  separate; the ``rankings()`` feed hands back a single consensus scalar, which has had precisely
  that signal averaged out of it.
* **ECR and μ are no longer the same ordering.** Pre-Tier-1, μ was ``max(0, 300 − ecr)`` — a
  monotone function of the very variable the tiers were cut on, so cutting on one and pricing the
  drop in the other was self-consistent. μ is now real nflverse xEP under the JAAFFL map:
  Spearman(ECR, μ) = **−0.943** over 447 players, and the disagreement lands exactly where cliffs
  live — the μ-best WR ranks 39.5 by ECR, and the ECR-best QB is only μ-rank 11. Cutting on ECR
  while asking "who is the weakest *by MLV*" mixes two orderings. Free ECR is also PPR-sourced
  (see ``precompute``) while this league is custom non-PPR; μ is scored under the exact map.
* **Tiering the whole board puts every boundary below replacement.** ``MLV`` on an empty roster is
  ``max(0, μ_p − baseline_pos)``, and the baseline IS the last startable player — so exactly
  ``(starting slots − positions)`` players clear it: **102 of 510** for this league (9×12 starters
  − 6). A boundary below that rank prices ``max(0.0, 0.00 − 0.00)`` *by construction*, which is
  what all 8 of them did. Sorting by value puts the largest drops at the top of the board where
  they can actually pay, so this needs no separate "draftable subset" parameter.

A cliff that is zero because both sides sit below replacement is a **legitimately computed** zero,
not a degraded one: below replacement a player adds nothing to the starting lineup, so there is no
urgency to price. ``league.coverage.inert_cliff_positions`` is the guard that tells the two apart.

Determinism is now unconditional (no ``random_state``): sorting and gap selection are exact.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Mapping

from jaaffl.domain import Position


def assign_tiers(
    value: Mapping[str, float],
    position: Mapping[str, Position],
    *,
    max_tiers_per_pos: int = 8,
) -> dict[str, int]:
    """Per position: sort by ``value`` descending and break where the drop to the next player
    exceeds that position's MEAN adjacent drop, keeping the largest such drops up to
    ``max_tiers_per_pos`` tiers. Returns contiguous 1-indexed tiers (tier 1 = best).

    ``value`` is projected league points (μ), NOT ECR — higher is better. See the module docstring
    for the measured reason that differs from §3.6's letter.

    The mean is the whole threshold: it is computed from the position's own curve, so a steep RB
    board and a flat kicker board are each judged on their own scale, and no constant is invented.
    A perfectly uniform position has no drop that stands out and correctly yields ONE tier — the
    honest "this position has no tier structure" rather than a ladder of arbitrary singletons.

    There is deliberately no minimum tier size. Measured on the live 2026 board, requiring three
    players per tier erases the two largest real cliffs on it (TE1 sits 43.88 points clear of TE2,
    RB1 40.13 clear of RB2) by folding those outliers into a group. A one-player tier is not
    degenerate when one player really is that far ahead.
    """
    by_pos: dict[Position, list[str]] = defaultdict(list)
    for pid, pos in position.items():
        if pid in value:
            by_pos[pos].append(pid)

    tiers: dict[str, int] = {}
    for pids in by_pos.values():
        # Ties broken by id so the tier map is reproducible across runs and dict orderings.
        ranked = sorted(pids, key=lambda p: (-value[p], p))
        gaps = [(value[ranked[i]] - value[ranked[i + 1]], i) for i in range(len(ranked) - 1)]
        breaks: set[int] = set()
        if gaps:
            mean_gap = sum(gap for gap, _ in gaps) / len(gaps)
            steep = sorted(
                ((gap, i) for gap, i in gaps if gap > mean_gap), key=lambda g: (-g[0], g[1])
            )
            breaks = {i for _gap, i in steep[: max(0, max_tiers_per_pos - 1)]}

        tier = 1
        for i, pid in enumerate(ranked):
            tiers[pid] = tier
            if i in breaks:
                tier += 1
    return tiers


def cliff_bonuses(
    tiers: Mapping[str, int],
    mlv: Mapping[str, float],
    position: Mapping[str, Position],
) -> dict[str, float]:
    """CliffBonus_p = MLV_p − MLV(best player in the next tier down at pos(p)) if p is the WEAKEST
    (lowest-MLV) player in its tier, else 0.0 (design §6.C.6). The bottom tier's last player has no
    tier below → 0.0. Clamped to ≥ 0 — a cliff is urgency, never a penalty (Score adds α·Cliff).

    Measured in MLV rather than raw μ on purpose: below replacement MLV floors at 0, so a drop
    between two players who both fail to crack the starting lineup correctly prices to nothing.
    """
    bonuses: dict[str, float] = dict.fromkeys(tiers, 0.0)

    by_pos_tier: dict[tuple[Position, int], list[str]] = defaultdict(list)
    for pid, tier in tiers.items():
        by_pos_tier[(position[pid], tier)].append(pid)

    for (pos, tier), members in by_pos_tier.items():
        next_tier = by_pos_tier.get((pos, tier + 1))
        if not next_tier:  # bottom tier at this position → no cliff below
            continue
        last_in_tier = min(members, key=lambda p: mlv[p])  # weakest of this tier
        best_next = max(mlv[q] for q in next_tier)
        bonuses[last_in_tier] = max(0.0, mlv[last_in_tier] - best_next)
    return bonuses
